// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSsfU8EOzJLWpr9__l-Ts7jgItp6wPTds',
    appId: '1:1081326301443:web:dc22351c26f4b67fd4b936',
    messagingSenderId: '1081326301443',
    projectId: 'myapp-70217',
    authDomain: 'myapp-70217.firebaseapp.com',
    storageBucket: 'myapp-70217.appspot.com',
    measurementId: 'G-EPM03287VZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzYoUh0gPNc69vMVrggw_zwTHW30gmOSs',
    appId: '1:1081326301443:android:f10bbdb084fe2072d4b936',
    messagingSenderId: '1081326301443',
    projectId: 'myapp-70217',
    storageBucket: 'myapp-70217.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvoTlO1YxOY9O8pGCMU-mkWpLQouYJCUY',
    appId: '1:1081326301443:ios:9abb709716e8a700d4b936',
    messagingSenderId: '1081326301443',
    projectId: 'myapp-70217',
    storageBucket: 'myapp-70217.appspot.com',
    iosClientId: '1081326301443-n8o87bcci737ue20g8cq0kg23m8bocpa.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvoTlO1YxOY9O8pGCMU-mkWpLQouYJCUY',
    appId: '1:1081326301443:ios:9abb709716e8a700d4b936',
    messagingSenderId: '1081326301443',
    projectId: 'myapp-70217',
    storageBucket: 'myapp-70217.appspot.com',
    iosClientId: '1081326301443-n8o87bcci737ue20g8cq0kg23m8bocpa.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );
}
